### ISSUE TITLE
Upgrade aws-efs-operator's 0.0.5 to support  dynamic provisioning of AWS EFS

### ISSUE THREAD

**Issue by amej** [openshift/aws-efs-operator#36]
AWS EFS Operator 0.0.5 provided by Red Hat is pointing towards 9  months old tag: https://quay.io/repository/app-sre/aws-efs-operator?tag=4bc180b

The existing [Amazon EFS CSI driver](https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/release-1.3 ) supports dynamic provisioning.

Please upgrade the AWS EFS Operator.

**Comment by 2uasimojo** [comment]
cf. https://coreos.slack.com/archives/CCX9DB894/p1623343446111700

**Comment by 2uasimojo** [comment]
I think we have at least two steps available here:
1. Bump the driver and fix up any regressions to retain functional parity with what we have today.
2. Actually support dynamic provisioning in some way.

I can see the first thing happening. The second thing... maybe not so much, considering efforts underway to ship an officially-supported build of the driver with OCP.

**Comment by jharrington22** [comment]
Yes I'd agree that 1 is a possibility and for 2 I'd have to look at what the new driver is providing and if we consider it to be feature complete with what we'd expect from dynamic provisioning and OSD. We also need to consider OSD documentation updates etc. 

As @2uasimojo said there is work from OCP to ship an officially support version of the driver with OCP.

**Comment by amej** [comment]
> Yes I'd agree that 1 is a possibility and for 2 I'd have to look at what the new driver is providing and if we consider it to be feature complete with what we'd expect from dynamic provisioning and OSD. We also need to consider OSD documentation updates etc.

I installed this driver https://github.com/kubernetes-sigs/aws-efs-csi-driver/tree/release-1.3 within my company's OSD account.  
EFS Filesystems had to be pre-created.   Upon creation of the Openshift PVC; the EFS access point got automatically created within the EFS filesystem.

I am interested to understand the highlights of the complete feature set expected from dynamic provisioning offered in the OSD.

**Comment by 2uasimojo** [comment]
Here's the RFE for including the driver in OCP: https://github.com/openshift/enhancements/pull/687

To my understanding, that just gets you... the driver. You would have to do the rest manually as you described above.

**Comment by amej** [comment]
Thank you.  I am closing this issue and keeping track of my request in https://github.com/openshift/enhancements/pull/687
