### ISSUE TITLE
Does  aws-efs-operator's 0.0.8  support dynamic provisioning of AWS ?

### ISSUE THREAD

**Issue by amej** [openshift/aws-efs-operator#45]
This is a followup on my filed issue for aws-efs-operator 0.0.5  https://github.com/openshift/aws-efs-operator/issues/36
It was dependent upon the Openshift RFE   https://github.com/openshift/enhancements/pull/687 .  This has been merged. 
In the OperatorHub, I see AWS EFS Operator 0.0.8 provided by Red Hat pointing to container image sha256sum:  9c87267
Does this   aws-efs-operator's 0.0.8  support dynamic provisioning of AWS ?

**Comment by 2uasimojo** [comment]
It is extremely unlikely that this operator will ever be enhanced to support dynamic provisioning. I think we're just keeping it around in bugfix-only mode in case any existing customers are still using it. Your best bet would be to raise this issue with the supported solution that took over from this one via the cited enhancement: https://github.com/openshift/aws-efs-csi-driver-operator

@jharrington22 feel free to reopen if you disagree.
